import {
  StatCard,
  ChartDataPoint,
  Candidate,
  Department,
  JobVacancy,
} from './types'

// Dashboard Stat Cards
export const dashboardStats: StatCard[] = [
  {
    id: '1',
    title: '10.000',
    label: 'Dalam Review',
    count: 10000,
    date: 'Juni 2023',
  },
  {
    id: '2',
    title: '800',
    label: 'Daftar Terpilih',
    count: 800,
    date: 'Juni 2023',
  },
  {
    id: '3',
    title: '800',
    label: 'Interview',
    count: 800,
    date: 'Juni 2023',
  },
  {
    id: '4',
    title: '3000',
    label: 'Tahap Tes',
    count: 3000,
    date: 'Juni 2023',
  },
  {
    id: '5',
    title: '100',
    label: 'Tahap Offering',
    count: 100,
    date: 'Juni 2023',
  },
  {
    id: '6',
    title: '100',
    label: 'Diterima',
    count: 100,
    date: 'Juni 2023',
  },
]

// Chart Data
export const chartData: ChartDataPoint[] = [
  { month: 'Jan', fulfilled: 65, notFulfilled: 85 },
  { month: 'Feb', fulfilled: 70, notFulfilled: 50 },
  { month: 'Mar', fulfilled: 45, notFulfilled: 55 },
  { month: 'Apr', fulfilled: 80, notFulfilled: 85 },
  { month: 'Mei', fulfilled: 75, notFulfilled: 80 },
  { month: 'Jun', fulfilled: 70, notFulfilled: 45 },
]

// Candidates List
export const candidatesList: Candidate[] = [
  {
    id: '1',
    name: 'Dhimas Adit',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop',
    department: 'QA (Quality Assurance)',
    position: 'QA Engineer',
    dateTime: 'Dec 22, 2022 10:45 WIB',
    status: 'Pending Interview',
    matchScore: 94,
    description: 'Senior QA Engineer, 5+ years testing experience, SDET expertise',
    strengths: ['Expertise in automated testing frameworks', 'Strong SQL & database knowledge', 'Excellent problem-solving skills'],
    weaknesses: ['Limited experience with CI/CD pipelines', 'Needs Python proficiency improvement'],
    aiSummary: 'Dhimas is an excellent match for this role. With 5+ years of QA experience and strong technical skills in automation, he can contribute immediately. His expertise in multiple testing frameworks and SQL makes him valuable for complex test scenarios. Recommendation: Interview and move forward.',
  },
  {
    id: '2',
    name: 'Sarah Johnson',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop',
    department: 'QA (Quality Assurance)',
    position: 'QA Lead',
    dateTime: 'Dec 20, 2022 14:30 WIB',
    status: 'Pending Interview',
    matchScore: 87,
    description: 'QA Lead with team management skills, API testing specialist',
    strengths: ['Team leadership experience', 'Strong API testing knowledge', 'Excellent communication skills'],
    weaknesses: ['Limited mobile testing experience', 'No automation framework development'],
    aiSummary: 'Sarah brings valuable leadership experience and solid technical skills. Her background in API testing and team management aligns well with the lead position. She would be a good fit for mentoring junior QA staff. Recommendation: Schedule technical interview.',
  },
  {
    id: '3',
    name: 'Mike Chen',
    avatar: 'https://images.unsplash.com/photo-1516030215669-9d1b92bdcb39?w=400&h=400&fit=crop',
    department: 'QA (Quality Assurance)',
    position: 'QA Automation Engineer',
    dateTime: 'Dec 18, 2022 09:15 WIB',
    status: 'Pending Interview',
    matchScore: 92,
    description: 'Senior automation engineer, Selenium & Appium expert, 7 years experience',
    strengths: ['Deep automation framework expertise', 'Proficiency in multiple programming languages', 'Strong performance testing skills'],
    weaknesses: ['Limited manual testing background', 'Less experience with agile methodologies'],
    aiSummary: 'Mike is a strong technical candidate with deep expertise in test automation. His 7 years of experience and mastery of popular automation tools make him highly qualified. He can immediately contribute to automation roadmap. Recommendation: Priority interview.',
  },
  {
    id: '4',
    name: 'Emily Rodriguez',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop',
    department: 'QA (Quality Assurance)',
    position: 'QA Engineer',
    dateTime: 'Dec 15, 2022 11:20 WIB',
    status: 'Pending Interview',
    matchScore: 78,
    description: 'Mid-level QA Engineer, 3 years experience, test case design specialist',
    strengths: ['Excellent test case design skills', 'Detail-oriented approach', 'Good documentation practices'],
    weaknesses: ['Limited automation experience', 'Needs advanced SQL knowledge'],
    aiSummary: 'Emily shows promise as a QA engineer with solid fundamentals in test design and documentation. She would benefit from mentorship in automation tools but has the right mindset. Good fit for mid-level position with growth potential. Recommendation: Interview with senior QA present.',
  },
  {
    id: '5',
    name: 'Alex Kumar',
    avatar: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=400&h=400&fit=crop',
    department: 'QA (Quality Assurance)',
    position: 'QA Analyst',
    dateTime: 'Dec 12, 2022 16:45 WIB',
    status: 'Pending Interview',
    matchScore: 85,
    description: 'QA Analyst with 4 years experience, defect management specialist',
    strengths: ['Excellent defect analysis skills', 'Strong attention to detail', 'Good stakeholder communication'],
    weaknesses: ['Limited technical testing skills', 'Minimal automation background'],
    aiSummary: 'Alex brings solid QA analysis skills and strong defect management experience. While lacking in automation, his analytical approach and communication skills are valuable. Could work well for test planning and coordination role. Recommendation: Consider for analyst position.',
  },
  {
    id: '6',
    name: 'Jessica Lee',
    avatar: 'https://images.unsplash.com/photo-1487180144351-b8472da7d491?w=400&h=400&fit=crop',
    department: 'QA (Quality Assurance)',
    position: 'Senior QA Engineer',
    dateTime: 'Dec 10, 2022 13:00 WIB',
    status: 'Pending Interview',
    matchScore: 96,
    description: 'Senior QA Engineer, 8+ years experience, test strategy expert, agile certified',
    strengths: ['Comprehensive test strategy expertise', 'Agile & DevOps proficiency', 'Mentoring and team building experience'],
    weaknesses: ['Recently transitioning from management back to IC', 'Some newer framework knowledge needed'],
    aiSummary: 'Jessica is an exceptional candidate with 8+ years of QA expertise and strategic thinking. Her agile certification and team mentoring experience add significant value. Slight learning curve on latest frameworks but strong foundational skills. Recommendation: Priority hire - offer competitive package.',
  },
]

// Departments
export const departmentsList: Department[] = [
  {
    id: '1',
    name: 'Purchasing',
    employeeCount: 50,
    capacity: 70,
    status: 'Pending',
  },
  {
    id: '2',
    name: 'Production',
    employeeCount: 50,
    capacity: 70,
    status: 'Pending',
  },
  {
    id: '3',
    name: 'Quality Assurance',
    employeeCount: 50,
    capacity: 70,
    status: 'Pending',
  },
  {
    id: '4',
    name: 'Warehouse',
    employeeCount: 50,
    capacity: 60,
    status: 'Fulfilled',
  },
  {
    id: '5',
    name: 'IT',
    employeeCount: 50,
    capacity: 70,
    status: 'Pending',
  },
  {
    id: '6',
    name: 'PPIC',
    employeeCount: 50,
    capacity: 70,
    status: 'Pending',
  },
  {
    id: '7',
    name: 'General Affairs',
    employeeCount: 50,
    capacity: 70,
    status: 'Fulfilled',
  },
  {
    id: '8',
    name: 'HRD',
    employeeCount: 10,
    capacity: 20,
    status: 'Fulfilled',
  },
]

// Job Vacancies
export const jobVacancies: JobVacancy[] = [
  {
    id: '1',
    title: 'UI UX Designer Intern',
    company: 'UMURAVA.AFRICA',
    salary: 'IDR 600,000 - 1,600,000/Month',
    department: 'Design',
    experience: 'Less than 1 year of experience',
    applicants: 170,
    applicantCount: 170,
    applicantDate: 'post of 22 Des 2022',
    image: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=500&h=300&fit=crop',
  },
  {
    id: '2',
    title: 'Production',
    company: 'UMURAVA.AFRICA',
    salary: 'IDR 600,000 - 1,600,000/Month',
    department: 'Production',
    experience: 'Less than 1 year of experience',
    applicants: 170,
    applicantCount: 170,
    applicantDate: 'post of 22 Des 2022',
    image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=500&h=300&fit=crop',
  },
  {
    id: '3',
    title: 'Quality Assurance',
    company: 'UMURAVA.AFRICA',
    salary: 'IDR 600,000 - 1,600,000/Month',
    department: 'Quality Assurance',
    experience: 'Less than 1 year of experience',
    applicants: 170,
    applicantCount: 170,
    applicantDate: 'post of 22 Des 2022',
    image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=500&h=300&fit=crop',
  },
  {
    id: '4',
    title: 'Warehouse',
    company: 'UMURAVA.AFRICA',
    salary: 'IDR 600,000 - 1,600,000/Month',
    department: 'Warehouse',
    experience: 'Less than 1 year of experience',
    applicants: 170,
    applicantCount: 170,
    applicantDate: 'post of 22 Des 2022',
    image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=500&h=300&fit=crop',
  },
]
